services:
  - type: web
    name: trippool-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 1 --timeout 120"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: RENDER
        value: "true"
